image:
  - Visual Studio 2019

artifacts:
  - path: build.7z
    name: build.7z

init:
  - echo %cd%

build_script:
  - run2.bat build
    #  - 7z a -t7z -mx9 -y build.7z build\
    #  - 7z l build.7z
